CREATE TABLE habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT habits_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

CREATE INDEX habits_user_id_idx ON habits(user_id);
