ALTER TABLE habits ADD COLUMN created_on DATE NOT NULL
    DEFAULT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw' AS DATE);

CREATE TABLE habit_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id BIGINT NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
    completion_date DATE NOT NULL,
    CONSTRAINT habit_completions_habit_date_unique UNIQUE (habit_id, completion_date)
);
