CREATE TABLE habit_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id BIGINT NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
    target_days INTEGER NOT NULL CHECK (target_days BETWEEN 1 AND 7),
    effective_from DATE NOT NULL,
    CONSTRAINT habit_targets_habit_date_unique UNIQUE (habit_id, effective_from)
);

INSERT INTO habit_targets(habit_id, target_days, effective_from)
SELECT id, 7, CAST(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw' AS DATE) FROM habits;
