CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (TRIM(title) <> ''),
    points INTEGER NOT NULL CHECK (points > 0),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    in_focus BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO tasks (title, points) VALUES
    ('Poświęcić 20 minut na naukę Reacta', 20),
    ('Wybrać się na spacer', 15),
    ('Przeczytać rozdział książki', 10);
