CREATE TABLE rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (TRIM(title) <> ''),
    cost INTEGER NOT NULL CHECK (cost > 0)
);

INSERT INTO rewards (title, cost) VALUES
    ('Odcinek ulubionego serialu', 20),
    ('Godzina grania', 40),
    ('Wieczór filmowy', 60);
