CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    points BIGINT NOT NULL DEFAULT 0
);

INSERT INTO users (name, points)
SELECT 'Gracz', COALESCE(SUM(points), 0) FROM tasks WHERE completed = TRUE;

ALTER TABLE tasks ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1 REFERENCES users(id);
CREATE INDEX tasks_user_id_idx ON tasks(user_id);

CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    reward_id BIGINT NOT NULL REFERENCES rewards(id),
    title TEXT NOT NULL,
    cost INTEGER NOT NULL CHECK (cost > 0)
);
CREATE INDEX purchases_user_id_idx ON purchases(user_id);
