CREATE TABLE account_email (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    verified_email VARCHAR(254) UNIQUE,
    pending_email VARCHAR(254),
    token_hash VARCHAR(64) UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE,
    last_sent_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE email_send_lock (id INTEGER PRIMARY KEY);
INSERT INTO email_send_lock (id) VALUES (1);

CREATE TABLE email_send_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_hash VARCHAR(64) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX email_send_event_time ON email_send_event(sent_at);

CREATE TABLE email_notification (
    id VARCHAR(36) PRIMARY KEY,
    recipient VARCHAR(254) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL
);
