# Use with: ./mvnw spring-boot:run -Dspring-boot.run.profiles=local
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/quest_todo
spring.datasource.username=quest_todo
spring.datasource.password=quest_todo_local
