spring.application.name=QuestTodo
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/quest_todo}
spring.datasource.username=${DB_USER:quest_todo}
spring.datasource.password=${DB_PASSWORD:quest_todo_local}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
